Repository carresemata/xtillion_healthgrades_migration, pull requests merged in 2024-07, with the labels that each got.

#300 new view in show schema
  migration_original/ODS1Stage/views/Show/vwuPracticingSpecialtyToGroupSpecialtyPrimary/spu_original_vwuPracticingSpecialtyToGroupSpecialtyPrimary.txt
  migration_original/ODS1Stage/views/Show/vwuPracticingSpecialtyToGroupSpecialtyPrimary/spu_translated_vwuPracticingSpecialtyToGroupSpecialtyPrimary.sql
Labels: show schema

#303 show.solrprovider (xml load 1/3)
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
Labels: show schema

#307 Show.SOLRProvider
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
Labels: bug, validation

#298 mid.practicesponsorship
  migration_original/ODS1Stage/tables/Mid/PracticeSponsorship/MID.PRACTICESPONSORSHIP-report.md
  migration_original/ODS1Stage/tables/Mid/PracticeSponsorship/spu_translated_PracticeSponsorship.sql
Labels: validation, mid schema

#304 base.cliententitytoclientfeature
  migration_original/ODS1Stage/tables/Base/ClientEntityToClientFeature/spu_translated_ClientEntityToClientFeature.sql
Labels: enhancement, base schema

#305 mid.facility
  migration_original/ODS1Stage/tables/Mid/Facility/spu_translated_Facility.sql
Labels: enhancement, mid schema

#239 base.clientproductentitytodisplaypartnerphone
  migration_original/ODS1Stage/tables/Base/ClientProductEntityToDisplayPartnerPhone/BASE.CLIENTPRODUCTENTITYTODISPLAYPARTNERPHONE-report.md
  migration_original/ODS1Stage/tables/Base/ClientProductEntityToDisplayPartnerPhone/spu_translated_ClientProductEntityToDisplayPartnerPhone.sql
Labels: validation, base schema

#309 Refactor UUID generation
  migration_original/ODS1Stage/functions/Utils/generate_uuid.sql
  migration_original/ODS1Stage/tables/Base/Address/spu_translated_Address.sql
  migration_original/ODS1Stage/tables/Base/CityStatePostalCode/spu_translated_CityStatePostalCode.sql
  migration_original/ODS1Stage/tables/Base/Client/spu_translated_Client.sql
  migration_original/ODS1Stage/tables/Base/ClientEntityToClientFeature/spu_translated_ClientEntityToClientFeature.sql
  migration_original/ODS1Stage/tables/Base/ClientFeatureToClientFeatureValue/spu_translated_ClientFeatureToClientFeatureValue.sql
  migration_original/ODS1Stage/tables/Base/ClientProductEntityRelationship/spu_translated_ClientProductEntityRelationship.sql
  migration_original/ODS1Stage/tables/Base/ClientProductEntityToDisplayPartnerPhone/spu_translated_ClientProductEntityToDisplayPartnerPhone.sql
  migration_original/ODS1Stage/tables/Base/ClientProductEntityToPhone/spu_translated_ClientProductEntityToPhone.sql
  migration_original/ODS1Stage/tables/Base/ClientProductToCallCenter/spu_translated_ClientProductToCallCenter.sql
  migration_original/ODS1Stage/tables/Base/ClientProductToEntity/spu_translated_ClientProductToEntity.sql
  migration_original/ODS1Stage/tables/Base/ClientProductToPartner/spu_translated_ClientProductToPartner.sql
  migration_original/ODS1Stage/tables/Base/ClientToProduct/spu_translated_ClientToProduct.sql
  migration_original/ODS1Stage/tables/Base/Degree/spu_translated_Degree.sql
  migration_original/ODS1Stage/tables/Base/Facility/spu_translated_Facility.sql
  migration_original/ODS1Stage/tables/Base/FacilityHours/spu_translated_FacilityHours.sql
  migration_original/ODS1Stage/tables/Base/FacilityImage/spu_translated_FacilityImage.sql
  migration_original/ODS1Stage/tables/Base/FacilityToAddress/spu_translated_FacilityToAddress.sql
  migration_original/ODS1Stage/tables/Base/FacilityToFacilityType/spu_translated_FacilityToFacilityType.sql
  migration_original/ODS1Stage/tables/Base/Image/spu_translated_Image.sql
  migration_original/ODS1Stage/tables/Base/Office/spu_translated_Office.sql
  migration_original/ODS1Stage/tables/Base/OfficeHours/spu_translated_OfficeHours.sql
  migration_original/ODS1Stage/tables/Base/OfficeToAddress/spu_translated_OfficeToAddress.sql
  migration_original/ODS1Stage/tables/Base/OfficeToPhone/spu_translated_OfficeToPhone.sql
  migration_original/ODS1Stage/tables/Base/PartnerToEntity/spu_translated_PartnerToEntity.sql
  migration_original/ODS1Stage/tables/Base/Phone/spu_translated_Phone.sql
  migration_original/ODS1Stage/tables/Base/Practice/spu_translated_Practice.sql
  migration_original/ODS1Stage/tables/Base/Provider/spu_translated_Provider.sql
  migration_original/ODS1Stage/tables/Base/ProviderEmail/spu_translated_ProviderEmail.sql
  migration_original/ODS1Stage/tables/Base/ProviderIdentification/spu_translated_ProviderIdentification.sql
  migration_original/ODS1Stage/tables/Base/ProviderImage/spu_translated_ProviderImage.sql
  migration_original/ODS1Stage/tables/Base/ProviderLicense/spu_translated_ProviderLicense.sql
  migration_original/ODS1Stage/tables/Base/ProviderMalpractice/spu_translated_ProviderMalpractice.sql
  migration_original/ODS1Stage/tables/Base/ProviderMedia/spu_translated_ProviderMedia.sql
  migration_original/ODS1Stage/tables/Base/ProviderSanction/spu_translated_ProviderSanction.sql
  migration_original/ODS1Stage/tables/Base/ProviderSurveySuppression/spu_translated_ProviderSurveySuppression.sql
  migration_original/ODS1Stage/tables/Base/ProviderToAboutMe/spu_translated_ProviderToAboutMe.sql
  migration_original/ODS1Stage/tables/Base/ProviderToAppointmentAvailability/spu_translated_ProviderToAppointmentAvailability.sql
  migration_original/ODS1Stage/tables/Base/ProviderToCertificationSpecialty/spu_translated_ProviderToCertificationSpecialty.sql
  migration_original/ODS1Stage/tables/Base/ProviderToClientProductToDisplayPartner/spu_translated_ProviderToClientProductToDisplayPartner.sql
  migration_original/ODS1Stage/tables/Base/ProviderToClinicalFocus/spu_translated_ProviderToClinicalFocus.sql
  migration_original/ODS1Stage/tables/Base/ProviderToDegree/spu_translated_ProviderToDegree.sql
  migration_original/ODS1Stage/tables/Base/ProviderToDisplaySpecialty/spu_translated_ProviderToDisplaySpecialty.sql
  migration_original/ODS1Stage/tables/Base/ProviderToEducationInstitution/spu_translated_ProviderToEducationInstitution.sql
  migration_original/ODS1Stage/tables/Base/ProviderToFacility/spu_translated_ProviderToFacility.sql
  migration_original/ODS1Stage/tables/Base/ProviderToHealthInsurance/spu_translated_ProviderToHealthInsurance.sql
  migration_original/ODS1Stage/tables/Base/ProviderToLanguage/spu_translated_ProviderToLanguage.sql
  migration_original/ODS1Stage/tables/Base/ProviderToMAPCustomerProduct/spu_translated_ProviderToMAPCustomerProduct.sql
  migration_original/ODS1Stage/tables/Base/ProviderToOffice/spu_translated_ProviderToOffice.sql
  migration_original/ODS1Stage/tables/Base/ProviderToProviderSubType/spu_translated_ProviderToProviderSubType.sql
  migration_original/ODS1Stage/tables/Base/ProviderToProviderType/spu_translated_ProviderToProviderType.sql
  migration_original/ODS1Stage/tables/Base/ProviderToSpecialty/spu_translated_ProviderToSpecialty.sql
  migration_original/ODS1Stage/tables/Base/ProviderToSubStatus/spu_translated_ProviderToSubStatus.sql
  migration_original/ODS1Stage/tables/Base/ProviderToTelehealthMethod/spu_translated_ProviderToTelehealthMethod.sql
  migration_original/ODS1Stage/tables/Base/ProviderTraining/spu_translated_ProviderTraining.sql
  migration_original/ODS1Stage/tables/Base/ProviderURL/spu_translated_ProviderURL.sql
  migration_original/ODS1Stage/tables/Base/ProviderVideo/spu_translated_ProviderVideo.sql
  migration_original/ODS1Stage/tables/Base/TelehealthMethod/spu_translated_TelehealthMethod.sql
  migration_original/ODS1Stage/tables/Base/URL/spu_translated_URL.sql
Labels: enhancement

#311 Show.SOLRProviderAddress
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
  migration_original/ODS1Stage/tables/Show/SOLRProviderAddress/SHOW.SOLRPROVIDERADDRESS-report.md
  migration_original/ODS1Stage/tables/Show/SOLRProviderAddress/spu_translated_SOLRProviderAddress.sql
Labels: validation, show schema

#312 Midpractice
  migration_original/ODS1Stage/tables/Mid/Practice/MID.PRACTICE-report.md
  migration_original/ODS1Stage/tables/Mid/Practice/spu_translated_Practice.sql
Labels: bug, mid schema

#316 Latest Version of SOLRProvider with most XMLs
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
Labels: bug, enhancement

#318 base.image
  migration_original/ODS1Stage/tables/Base/Image/spu_translated_Image.sql
Labels: bug

#310 show.solrpractice
  migration_original/ODS1Stage/tables/Show/SOLRPractice/SHOW.SOLRPRACTICE-report.md
  migration_original/ODS1Stage/tables/Show/SOLRPractice/spu_translated_SOLRPractice.sql
Labels: validation, show schema

#324 sponsorship and searchsponsorship xmls
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
Labels: show schema

#315 Debug providertomapcustomerproduct
  migration_original/ODS1Stage/tables/Base/ProviderToMAPCustomerProduct/BASE.PROVIDERTOMAPCUSTOMERPRODUCT-report.md
  migration_original/ODS1Stage/tables/Base/ProviderToMAPCustomerProduct/spu_translated_ProviderToMAPCustomerProduct.sql
  migration_original/other/validation_report.py
Labels: validation, base schema

#325 fixed processing time for mid facility
  migration_original/ODS1Stage/tables/Mid/Facility/spu_translated_Facility.sql
Labels: mid schema, fix

#317 Base.ProviderImage
  migration_original/ODS1Stage/tables/Base/ProviderImage/spu_translated_ProviderImage.sql
Labels: bug

#306 show.solrproviderredirect
  migration_original/ODS1Stage/tables/Show/SOLRProviderRedirect/SHOW.SOLRPROVIDERREDIRECT-report.md
  migration_original/ODS1Stage/tables/Show/SOLRProviderRedirect/spu_translated_SOLRProviderRedirect.sql
Labels: validation, show schema

#327 Update spu_translated_ClientProductEntityToDisplayPartnerPhone.sql
  migration_original/ODS1Stage/tables/Base/ClientProductEntityToDisplayPartnerPhone/spu_translated_ClientProductEntityToDisplayPartnerPhone.sql
Labels: bug, base schema

#321 Base.ProviderMalpractice Delta Fix
  migration_original/ODS1Stage/tables/Base/ProviderMalpractice/spu_translated_ProviderMalpractice.sql
Labels: bug

#328 base.providersurveysuppression
  migration_original/ODS1Stage/tables/Base/ProviderSurveySuppression/spu_translated_ProviderSurveySuppression.sql
Labels: bug

#326 show.solrproviderdelta
  migration_original/ODS1Stage/tables/Show/SOLRProviderDelta/spu_translated_SOLRProviderDelta.sql
Labels: validation, show schema

#322 Mid.ProviderSpecialtyFacilityServiceLineRating Delta Fix
  migration_original/ODS1Stage/tables/Base/ProviderMedia/spu_translated_ProviderMedia.sql
  migration_original/ODS1Stage/tables/Mid/ProviderSpecialtyFacilityServiceLineRating/spu_translated_ProviderSpecialtyFacilityServiceLineRating.sql
Labels: bug

#323 mid.providerpracticeoffice
  migration_original/ODS1Stage/tables/Mid/ProviderPracticeOffice/MID.PROVIDERPRACTICEOFFICE-report.md
  migration_original/ODS1Stage/tables/Mid/ProviderPracticeOffice/spu_translated_ProviderPracticeOffice.sql
Labels: bug

#329 hosp_directory fix
  migration_original/ODS1Stage/tables/Mid/ProviderSponsorship/spu_translated_ProviderSponsorship.sql
  migration_original/ODS1Stage/tables/Show/SOLRFacility/spu_translated_SOLRFacility.sql
  migration_original/ODS1Stage/views/ermart1/facility_vwufacilityhgdisplayprocedures/spu_translated_facility_vwufacilityhgdisplayprocedures.sql
Labels: bug

#330 Final dep july
  migration_original/ODS1Stage/tables/Show/SOLRProviderDelta/spu_translated_SOLRProviderDelta.sql
  migration_original/audit_sp_dependencies.json
  migration_original/other/audit_dependencies.py
  migration_original/other/audit_sp_dependencies.json
  migration_original/other/audit_table_dependencies.json
  migration_original/other/static_tables.txt
Labels: validation

#331 base_provider
  migration_original/ODS1Stage/tables/Base/Provider/spu_translated_Provider.sql
Labels: bug

#335 fix mid.providerlicense
  migration_original/ODS1Stage/tables/Mid/ProviderLicense/spu_translated_ProviderLicense.sql
Labels: bug, mid schema

#336 two util scripts
  migration_original/other/check_distinct_percentage.py
  migration_original/other/generate_main_proc.py
  migration_original/other/main_proc_script.txt
Labels: util

#333 base.providermedia
  migration_original/ODS1Stage/tables/Base/ProviderMedia/spu_translated_ProviderMedia.sql
Labels: bug

#334 base.providermalpractice
  migration_original/ODS1Stage/tables/Base/ProviderMalpractice/spu_translated_ProviderMalpractice.sql
Labels: bug

#332 show.solrpractice
  migration_original/ODS1Stage/tables/Show/SOLRPractice/spu_translated_SOLRPractice.sql
Labels: bug

#337 base.partnertoentity
  migration_original/ODS1Stage/tables/Base/PartnerToEntity/spu_translated_PartnerToEntity.sql
Labels: bug

#338 mid.partnerentity
  migration_original/ODS1Stage/tables/Mid/PartnerEntity/spu_translated_PartnerEntity.sql
Labels: bug

#340 show.solrprovider
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
Labels: bug

#342 show.solrfacility
  migration_original/ODS1Stage/tables/Show/SOLRFacility/spu_translated_SOLRFacility.sql
Labels: bug

#341 mid.providerfacility
  migration_original/ODS1Stage/tables/Mid/ProviderFacility/spu_translated_ProviderFacility.sql
Labels: bug

#343 midfacility fix
  migration_original/ODS1Stage/tables/Mid/Facility/spu_translated_Facility.sql
Labels: bug, mid schema

#345 mid.facllity
  migration_original/ODS1Stage/tables/Mid/Facility/spu_translated_Facility.sql
Labels: bug

#347 show.solrprovider
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
Labels: bug

#348 optimized mid facility
  migration_original/ODS1Stage/tables/Mid/Facility/spu_translated_Facility.sql
Labels: bug, mid schema

#349 Clean XML Utility Function
  migration_original/ODS1Stage/functions/Utils/clean_xml.sql
Labels: enhancement

#350 Clean Github Repo
  .DS_Store
  deliverables/orchestration/dags/__pycache__/orchestration.cpython-39.pyc
  deliverables/orchestration/dags/__pycache__/sso_test.cpython-39.pyc
  deliverables/orchestration/dags/data/sp_dependencies-2.json
  deliverables/orchestration/dags/data/traced_dependencies.json
  migration_original/ODS1Stage/functions/Utils/P_JSON_TO_XML.sql
  migration_original/ODS1Stage/functions/Utils/sp_archive_processing.sql
  migration_original/ODS1Stage/views/Base/vwuProviderSpecialty/spu_original_vwuProviderSpecialty.txt
  migration_original/ODS1Stage/views/Base/vwuProviderSpecialty/spu_translated_vwuProviderSpecialty.sql
  migration_original/ODS1Stage/views/Raw/VW_CUSTOMER_PRODUCT_PROFILE/spu_translated_VW_CUSTOMER_PRODUCT_PROFILE.sql
  migration_original/ODS1Stage/views/Raw/VW_FACILITY_PROFILE/spu_translated_VW_FACILITY_PROFILE.sql
  migration_original/ODS1Stage/views/Raw/VW_OFFICE_PROFILE/spu_translated_VW_OFFICE_PROFILE.sql
  migration_original/ODS1Stage/views/Raw/VW_PRACTICE_PROFILE/spu_translated_VW_PRACTICE_PROFILE.sql
  migration_original/ODS1Stage/views/Raw/VW_PROVIDER_PROFILE/spu_translated_VW_PROVIDER_PROFILE.sql
  migration_original/extract_concat_procedures.py
  migration_original/other/UDF.py
  migration_original/other/add_spu_per_table.py
  migration_original/other/audit_dependencies.py
  migration_original/other/audit_sp_dependencies.json
  migration_original/other/audit_table_dependencies.json
  migration_original/other/business_logic.xlsx
  migration_original/other/check_distinct_percentage.py
  migration_original/other/check_status.py
  migration_original/other/cleanup_folders.py
  migration_original/other/conditionals.py
  migration_original/other/create_final_folder.py
  migration_original/other/generate_main_proc.py
  migration_original/other/github_pull.sql
  migration_original/other/is_full.py
  migration_original/other/main_proc_script.txt
  migration_original/other/migration_folders.py
  migration_original/other/migration_status.xlsx
  migration_original/other/monitoring.py
  migration_original/other/orch_excel.py
  migration_original/other/orchestration.py
  migration_original/other/snowflake_push.py
  migration_original/other/sp_dependencies.json
  migration_original/other/sp_formatting.py
  migration_original/other/sp_load_default.sql
  migration_original/other/spus_update_tables.csv
  migration_original/other/static_tables.txt
  migration_original/other/status_repo.py
  migration_original/other/table_dependencies.json
  migration_original/other/table_dependencies.py
  migration_original/other/tables_ods1_stage.csv
  migration_original/other/validation.py
  migration_original/other/views_dependencies.json
  migration_original/refactor_xmls.py
Labels: documentation, enhancement

#351 fix views
  migration_original/ODS1Stage/views/Base/vw_swimlane_base_client/spu_translated_vw_swimlane_base_client.sql
  migration_original/ODS1Stage/views/Base/vwuClientProductEntityToPhone/spu_translated_vwuClientProductEntityToPhone.sql
  migration_original/ODS1Stage/views/Base/vwuPDCClientDetail/spu_translated_vwuPDCClientDetail.sql
  migration_original/ODS1Stage/views/Base/vwuPDCEmployedProviderPhone/spu_translated_vwuPDCEmployedProviderPhone.sql
  migration_original/ODS1Stage/views/Base/vwuPDCFacilityDetail/spu_translated_vwuPDCFacilityDetail.sql
  migration_original/ODS1Stage/views/Base/vwuProviderRecognition/spu_translated_vwuProviderRecognition.sql
  migration_original/ODS1Stage/views/Base/vwuProviderSpecialty/spu_translated_vwuProviderSpecialty.sql
  migration_original/ODS1Stage/views/Base/vwucallcenterdetails/spu_translated_vwucallcenterdetails.sql
  migration_original/ODS1Stage/views/Base/vwupdcpracticeofficedetail/spu_translated_vwupdcpracticeofficedetail.sql
  migration_original/ODS1Stage/views/Show/vwuPracticeIndex/spu_translated_vwuPracticeIndex.sql
  migration_original/ODS1Stage/views/Show/vwuPracticingSpecialtyToGroupSpecialtyPrimary/spu_translated_vwuPracticingSpecialtyToGroupSpecialtyPrimary.sql
  migration_original/ODS1Stage/views/Show/vwuProviderIndex/spu_translated_vwuProviderIndex.sql
  migration_original/ODS1Stage/views/ermart1/facility_vwufacilityhgdisplayprocedures/spu_translated_facility_vwufacilityhgdisplayprocedures.sql
Labels: enhancement

#352 fix sponsorship xml for solrprovider
  migration_original/ODS1Stage/tables/Show/SOLRProvider/spu_translated_SOLRProvider.sql
Labels: bug, show schema
